# Generated by Django 5.2.10 on 2026-03-11 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_click', 'Product Click'), ('category_click', 'Category Click'), ('store_click', 'Store Click'), ('page_view', 'Page View')], max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=200, null=True)),
                ('category_id', models.CharField(blank=True, max_length=200, null=True)),
                ('store_id', models.CharField(blank=True, max_length=200, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='store_event_event_t_820a61_idx'), models.Index(fields=['product_id'], name='store_event_product_86b9c9_idx'), models.Index(fields=['category_id'], name='store_event_categor_c29dda_idx'), models.Index(fields=['store_id'], name='store_event_store_i_c40a65_idx'), models.Index(fields=['created_at'], name='store_event_created_30a81b_idx')],
            },
        ),
    ]
