# Generated by Django 5.2.10 on 2026-02-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXECUTIVE', 'Executive'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer'), ('SUPPORT', 'Customer Support'), ('VENDOR', 'Vendor')], default='CUSTOMER', max_length=20),
        ),
    ]
